# Generated by Django 5.1 on 2024-08-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
    ]
